version: '3'

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge

services:
  server:
    build:
      context: server/build
      dockerfile: Dockerfile
    command: |
      sh -c "cd cmd/server && ls"

    networks:
      - backend

    ports:
      - '8080:8080'
    volumes:
      - ../server:/go/src/server/